In [18]:
import pandas as pd

In [201]:
sales = pd.read_csv("data/08_reporting/predictions.csv")

In [202]:
sales

,year,price,mpg,adjustedMileage,predicted_price,model,transmission,fuelType,tax,engineSize
0,2017,12000,57.7,15944,11250,Fiesta,Automatic,Petrol,150,1.0
1,2018,14000,57.7,9083,13839,Focus,Manual,Petrol,150,1.0
2,2017,13000,57.7,12456,12399,Focus,Manual,Petrol,150,1.0
3,2019,17500,40.3,10460,16283,Fiesta,Manual,Petrol,145,1.5
4,2019,16500,48.7,1482,15467,Fiesta,Automatic,Petrol,145,1.0
...,...,...,...,...,...,...,...,...,...,...
17907,2016,7999,54.3,31348,7496,Fiesta,Manual,Petrol,125,1.2
17908,2017,8999,47.1,16700,10901,B-MAX,Manual,Petrol,150,1.4
17909,2014,7499,57.7,40700,6245,B-MAX,Manual,Petrol,30,1.0
17910,2015,9999,67.3,7010,10122,Focus,Manual,Diesel,20,1.6
17911,2018,8299,57.7,5007,9510,KA,Manual,Petrol,145,1.2

In [178]:
ohc_columns = ['model', 'transmission', 'fuelType', 'tax', 'engineSize']

In [34]:
models = [ x for x in sales.columns if x.startswith('model_x_') ]

In [56]:
sales[models].iloc[0]

model_x_B-MAX                    0
model_x_C-MAX                    0
model_x_EcoSport                 0
model_x_Edge                     0
model_x_Escort                   0
model_x_Fiesta                   1
model_x_Focus                    0
model_x_Fusion                   0
model_x_Galaxy                   0
model_x_Grand C-MAX              0
model_x_Grand Tourneo Connect    0
model_x_KA                       0
model_x_Ka+                      0
model_x_Kuga                     0
model_x_Mondeo                   0
model_x_Mustang                  0
model_x_Puma                     0
model_x_Ranger                   0
model_x_S-MAX                    0
model_x_Streetka                 0
model_x_Tourneo Connect          0
model_x_Tourneo Custom           0
model_x_Transit Tourneo          0
Name: 0, dtype: int64

In [115]:
model_df = sales[models].copy()

In [116]:
model_df["model"]=None

In [117]:
model_df

,model_x_B-MAX,model_x_C-MAX,model_x_EcoSport,model_x_Edge,model_x_Escort,model_x_Fiesta,model_x_Focus,model_x_Fusion,model_x_Galaxy,model_x_Grand C-MAX,...,model_x_Mondeo,model_x_Mustang,model_x_Puma,model_x_Ranger,model_x_S-MAX,model_x_Streetka,model_x_Tourneo Connect,model_x_Tourneo Custom,model_x_Transit Tourneo,model
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,None
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,None
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None
4,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17907,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None
17908,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None
17909,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None
17910,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,None
17911,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None

In [88]:
for m in models:
    model_name = m.split('model_x_')[1]
    print(model_name)

B-MAX
C-MAX
EcoSport
Edge
Escort
Fiesta
Focus
Fusion
Galaxy
Grand C-MAX
Grand Tourneo Connect
KA
Ka+
Kuga
Mondeo
Mustang
Puma
Ranger
S-MAX
Streetka
Tourneo Connect
Tourneo Custom
Transit Tourneo

In [91]:
for m in models:
    model_name = m.split('model_x_')[1]
    model_df[model_df[m] == 1] = model_name

In [100]:
model_df['model_x_Fiesta'] == 1

0         True
1        False
2        False
3         True
4         True
         ...
17907     True
17908    False
17909    False
17910    False
17911    False
Name: model_x_Fiesta, Length: 17912, dtype: bool

In [109]:
model_df[model_df['model_x_Fiesta'] == 1]['model']="Fiesta"

[11/11/22 20:57:02] WARNING  /home/tonya/anaconda3/envs/kedro-environment/lib/python3.7/site-packag ]8;id=828167;file:///home/tonya/anaconda3/envs/kedro-environment/lib/python3.7/warnings.py\warnings.py]8;;\:]8;id=941202;file:///home/tonya/anaconda3/envs/kedro-environment/lib/python3.7/warnings.py#110\110]8;;\
                             es/ipykernel_launcher.py:1: SettingWithCopyWarning:
                             A value is trying to be set on a copy of a slice from a DataFrame.
                             Try using .loc[row_indexer,col_indexer] = value instead

                             See the caveats in the documentation:
                             https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#
                             returning-a-view-versus-a-copy
                               """Entry point for launching an IPython kernel.

In [110]:
mask = model_df['model_x_Fiesta'] == 1

In [113]:
model_df.loc[mask,"model"] = "Fiesta"

In [114]:
model_df

,model_x_B-MAX,model_x_C-MAX,model_x_EcoSport,model_x_Edge,model_x_Escort,model_x_Fiesta,model_x_Focus,model_x_Fusion,model_x_Galaxy,model_x_Grand C-MAX,...,model_x_Mondeo,model_x_Mustang,model_x_Puma,model_x_Ranger,model_x_S-MAX,model_x_Streetka,model_x_Tourneo Connect,model_x_Tourneo Custom,model_x_Transit Tourneo,model
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fiesta
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,None
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,None
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fiesta
4,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fiesta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17907,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fiesta
17908,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None
17909,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None
17910,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,None
17911,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,None

In [185]:
def _reverse_ohc(df_ohc: pd.DataFrame, ohc_column: str, cols: list) -> pd.DataFrame:
    """ 
        creates a DataFrame[ohc_column] where
            ohc_column: name of column before ohc, eg. model
            ohc_column will be set to the ohc column name where value = 1 
            column name will be extracted by removing the column prefix_sep, e.g.
                model_x_B-MAX -> B-MAX
            cols: list of columns created by ohc, e.g. [model_x_B-MAX , model_x_C-MAX, ....]

    """
    df = df_ohc[cols].copy()
    for c in cols:
        c_name = c.split(f'{ohc_column}_x_')[1]
        #print(c_name)
        mask = df[c] == 1
        df.loc[mask,ohc_column] = c_name
    return df.drop(cols, axis = 1)

In [186]:
def reverse_ohc(df_ohc: pd.DataFrame, ohc_columns: dict) -> pd.DataFrame:
    """ reverse the ohc to restore original columns 
        
    """

    #ohc_columns = ['model', 'transmission', 'fuelType', 'tax', 'engineSize']
    for ohc_column in ohc_columns:
        cols = [ x for x in sales.columns if x.startswith(f"{ohc_column}_x_") ]
        # cols -> [model_x_B-MAX , model_x_C-MAX, model_x_EcoSport, model_x_Edge, ....]
        non_ohc_col = _reverse_ohc(sales, ohc_column, cols)
        #print(non_ohc_col)
        df_ohc[ohc_column] = non_ohc_col
        df_ohc.drop(cols, axis = 1, inplace=True)
    return df_ohc

In [187]:
ohc_columns = ['model', 'transmission', 'fuelType', 'tax', 'engineSize']

In [190]:
s2 = reverse_ohc(sales,ohc_columns)

In [183]:
len(s2)

17912

In [191]:
s2

,year,price,mpg,adjustedMileage,normalizedPrice,predicted_price,model,transmission,fuelType,tax,engineSize
0,2017,12000,57.7,15944,98.149227,11250,Fiesta,Automatic,Petrol,150,1.0
1,2018,14000,57.7,9083,104.407253,13839,Focus,Manual,Petrol,150,1.0
2,2017,13000,57.7,12456,101.351601,12399,Focus,Manual,Petrol,150,1.0
3,2019,17500,40.3,10460,114.161412,16283,Fiesta,Manual,Petrol,145,1.5
4,2019,16500,48.7,1482,111.506152,15467,Fiesta,Automatic,Petrol,145,1.0
...,...,...,...,...,...,...,...,...,...,...,...
17907,2016,7999,54.3,31348,83.377442,7496,Fiesta,Manual,Petrol,125,1.2
17908,2017,8999,47.1,16700,87.429000,10901,B-MAX,Manual,Petrol,150,1.4
17909,2014,7499,57.7,40700,81.235287,6245,B-MAX,Manual,Petrol,30,1.0
17910,2015,9999,67.3,7010,91.214791,10122,Focus,Manual,Diesel,20,1.6
17911,2018,8299,57.7,5007,84.623799,9510,KA,Manual,Petrol,145,1.2