In [2]:
import pandas as pd

In [3]:
sales = pd.read_csv("data/07_model_output/engineered_sales_with_predictions.csv")

In [6]:
sales["actual_price"]=sales["actual_price"].astype(int)

In [7]:
sales

,year,price,mpg,adjustedMileage,normalizedPrice,model_B-MAX,model_C-MAX,model_EcoSport,model_Edge,model_Escort,...,engineSize_1.8,engineSize_2.0,engineSize_2.2,engineSize_2.3,engineSize_2.5,engineSize_3.2,engineSize_5.0,actual_price_normalised,actual_price,predicted_price
0,2017,12000,57.7,15944,98.149227,0,0,0,0,0,...,0,0,0,0,0,0,0,12000,2443162890,95.639623
1,2018,14000,57.7,9083,104.407253,0,0,0,0,0,...,0,0,0,0,0,0,0,14000,3623245663,103.925419
2,2017,13000,57.7,12456,101.351601,0,0,0,0,0,...,0,0,0,0,0,0,0,13000,2997912581,99.448100
3,2019,17500,40.3,10460,114.161412,0,0,0,0,0,...,0,0,0,0,0,0,0,17500,6409891015,110.917282
4,2019,16500,48.7,1482,111.506152,0,0,0,0,0,...,0,0,0,0,0,0,0,16500,5514676968,108.659302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17907,2016,7999,54.3,31348,83.377442,0,0,0,0,0,...,0,0,0,0,0,0,0,7999,866316408,81.222525
17908,2017,8999,47.1,16700,87.429000,1,0,0,0,0,...,0,0,0,0,0,0,0,8999,1170702748,94.437676
17909,2014,7499,57.7,40700,81.235287,1,0,0,0,0,...,0,0,0,0,0,0,0,7499,734552912,75.452049
17910,2015,9999,67.3,7010,91.214791,0,0,0,0,0,...,0,0,0,0,0,0,0,9999,1532592673,91.666017
17911,2018,8299,57.7,5007,84.623799,0,0,0,0,0,...,0,0,0,0,0,0,0,8299,951808132,89.396916